### ISSUE TITLE
3_MC_BuildingsArchetypes

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#36]
Dataset 3_MC_BuildingsArchetypes uses labels Oth-R32EU15 and Oth-R32EU12-H, while the classification is with the underscore:  Oth_R32EU15 and Oth_R32EU12-H. As consequence, the archetypes are not implemented for those two regions.

**Comment by nheeren** [comment]
I guess BuildME is to blame: https://github.com/nheeren/BuildME/blob/d32c1aaa607dc8da7e2b37ae6a20d635ca90ad95/BuildME/settings.py#L461-L480 

Let us coordinate for the next run soon @CarrerF

**Comment by stefanpauliuk** [comment]
Important observation @CarrerF !
--> I will go through the archetypes files and check that all regional labels match with the ones from the master classification. If not, correct and make an update for database version 2.5.

When importing the parameters, ODYM also checks and reports the number of matches. Obviously, I haven't paid close enough attention to the log file here. ODYM troughs no warning if it doesn't find data where there should be data, it then leaves the affected value at zero. It only throws an error if the entire classifications don't match. 
--> I will (not now, but later this spring) check and update the data parser to throw an error if it finds classification items that are not define in the master list.

**Comment by stefanpauliuk** [comment]
This error applies to all building archetype files. I now fixed it in the current version, @nheeren please make sure that buildME used the correct regional labels Oth_R32EU15 and Oth_R32EU12-H!

**Comment by nheeren** [comment]
> This error applies to all building archetype files. I now fixed it in the current version, @nheeren please make sure that buildME used the correct regional labels Oth_R32EU15 and Oth_R32EU12-H!

Certainly will https://github.com/nheeren/BuildME/issues/58
Do you intend to keep the region labels as they are for now?

**Comment by stefanpauliuk** [comment]
Fixed during major data update (re-calc and add non-res buildings) plus label fix.
