### ISSUE TITLE
4_PE_ProcessExtensions, SSP1 larger than SSP2

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#38]
Hi, I have revising the dataset I have stumbled upon this issue. All the production sectors, with few exceptions, have lower targets for SSP2 (and consequently LED*) than SSP1. I had a look at the the corresponding target table does not explain the rationale behind it.

*This was also surprising to me. In some parameters (for instance 4_PE_GHGIntensityEnergySupply, RCP) have more ambitious values in terms of emission cuts. Here, LED is on SSP2 level. Where does LED stand?

**Comment by stefanpauliuk** [comment]
Hi @CarrerF, this dataset is based on a ecoinvent scenario run that is not documented. As from our conversation, we will proceed with the following steps:
+ Simplfy the approach and consider change only along RCP dimension, not SSP anymore.
+ Extract GHG and CED for different materials from ecoinvent and use as 4_PE and 4_EI parameters.
    + BUT: then we woud have double-counting of GHG via 4_PE and 4_EI * GHG_Intensity_Energy_Supply.
    + So we either need to exclude 4_EI from the GHG calculation or subtract it from 4_PE
    + We can introduce a toggle flag in the model config to choose between the two cases, or report separate energy and GHG flows
+ Ideally, we also have a breakdown of CED into the RECC energy carriers to link them directly to the RECC energy supply scenario

**Comment by stefanpauliuk** [comment]
I agree @Hertwich , have prepared a proposal for building simple scenarios for material production GHG, see my email in a few minutes.

**Comment by stefanpauliuk** [comment]
Fixed during major update on how me model material production and energy supply.
