### ISSUE TITLE
4_PE_GHGIntensityEnergySupply, unrealistic trajectories

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#39]
The quality of the dataset should be discussed:
Quite often, the trajectories have
- increasing values even for SSP1 scenarios
![incr](https://user-images.githubusercontent.com/98351491/177200085-ef8e0c5d-c68f-4d2a-952c-17b97058d645.png)
![incr (2)](https://user-images.githubusercontent.com/98351491/177200088-47e31e74-8a36-4d50-ade7-fc100f5dbad8.png)

- RCP scenario have higher values than baseline (and late century explosion)
![high RCP (2)](https://user-images.githubusercontent.com/98351491/177200149-2a192a29-ebcf-40c3-876b-3f647d305608.png)
![high RCP](https://user-images.githubusercontent.com/98351491/177200164-d786fbfa-8dc3-4b52-aa81-836620961143.png)
![high RCP (3)](https://user-images.githubusercontent.com/98351491/177200181-32955b29-fce9-49d3-bbbf-59108d3b441a.png)

- unrealistic trajectories
![traj](https://user-images.githubusercontent.com/98351491/177200242-f010bc28-b29e-4248-b6a2-536d3116ac32.png)

I had a look a the original MESSAGE data and the corresponding parsing script. The GHG intensity is computed by dividing the total emissions by the final energy. The original trajectories are jumpy already, and scattered in time, which doesn't help. The energy carrier - final energy mapping is then done manually  in the parsing script.

I'm especially concerned about the late-century explosions of trajectories. I've questioning myself about the trajectories for some individual countries at the end of the time horizon [example: REB for France]
![Figure 14_GWP_TimeSeries_Materials_Stacked_France, LED, RCP2 6 energy mix png_France](https://user-images.githubusercontent.com/98351491/177202099-ac56659e-bace-4f64-8810-6f3ffce6b3b6.png)

**Comment by Hertwich** [comment]
Good catch. I think it is worthwhile to go through these issues when they produce undesirable or unrealistic outcomes. I would suggest that we look at ways to import data from new scenarios, e.g. the SHAPE scenario explorer. We are free to choose any of the models and do not need to stick to Message. However, using newer scenarios means that more people have worked on issues such as these from the IAM side.

**Comment by stefanpauliuk** [comment]
I agree! Although there have been quite a few updates and re-downloads of the MESSAGE-ix CD-LINKS project results. That parameter is among those with the highest number of revisions (more than 10).

Just to clarify: These emissions are supply chain emissions only from the generation/production of the individual fuels. The direct emissions from burning the coal, natural gas, etc, in one of our system's processes are calculated separately with 6_PR_DirectEmissions_V1.2

My suggestion is that you use your SHAPE project insights, also with the LCA method link, to explore improvement options for the GHG factors per unit of energy.

**Comment by stefanpauliuk** [comment]
The current implementation of energy supply (4_PE_ProcessExtensions_EnergyCarriers_V1.0) has no time and R-scenario aspect.

@CarrerF  , is there an update on this pending or shall we, for RECC v2.5, switch back to the MESSAGE energy supply results and invest a bit of time in understanding and fixing them?

current implementation:
`
# replicate 2015 values. The current dataset contains only the 2015 initial value. 
# Electricity is added separately in the next step
ParameterDict['4_PE_ProcessExtensions_EnergyCarriers_MJ_o'].Values         = np.einsum('nxo,n,tR->nxotR',  ParameterDict['4_PE_ProcessExtensions_EnergyCarriers'].Values[:,:,:,0],ParameterDict['4_EI_SpecificEnergy_EnergyCarriers'].Values,np.ones((Nt,NR)))
ParameterDict['4_PE_ProcessExtensions_EnergyCarriers_MJ_Materials'].Values = np.einsum('nxo,n,tRm->mnxotR',ParameterDict['4_PE_ProcessExtensions_EnergyCarriers'].Values[:,:,:,0],ParameterDict['4_EI_SpecificEnergy_EnergyCarriers'].Values,np.ones((Nt,NR,Nm)))

`

**Comment by CarrerF** [comment]
1. It's true, 4_PE_ProcessExtensions_EnergyCarriers has no time and R aspects as only 2015 values is available.
In the last update, I focused on electricity value because, together with direct emissions, they have larger contributions than indirect emissions. 

Switching back to IAM results is a possibility, if enough time can be invested (back to https://github.com/IndEcol/RECC-ODYM/issues/39#event-9184452530)
![image](https://user-images.githubusercontent.com/98351491/236689667-0dfe0d1c-cf3d-47c3-bf48-55f8ce7366de.png)

Also, IAM scenarios consistent with these GHG trajectories for environmental impacts other than GWP are missing.

2. I could not think of a meaningful way to model deployment of hydrogen. I considered converting hydrogen to electricity demand, yet this would not give the option to have hydrogen fully produced with renewable sources. As per the updates email,  I included hydrogen in 4_PE_ProcessExtensions_EnergyCarriers, with 0s as placeholder waiting for LCA results for all environmental impacts, even though I acknowledge that linking to the electricity might be a better solution.

**Comment by stefanpauliuk** [comment]
Allright, I'll think of a quick way to estimate hydrogen production impacts (likely going via the electricity demand), and then, we are all set for new results, and can iterate later on other improvements. But for now, all looks good, incuding the material footprint and process emissions calculations, really consistent, high quality and well documented work Fabio!
