### ISSUE TITLE
Buildings energy demand, 3_EI_Products_UsePhase_resbuildings_t

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#41]
In about lines 2394-2398, 
In the new update, historical cohorts'energy intensity is multiplied by RECC_System.ParameterDict['3_SHA_EnergyCarrierSplit_Buildings']. However, this multiplication occurred already in line 1577.
As consequence, hisotric energy intensity is set to 0:

![image](https://user-images.githubusercontent.com/98351491/218263178-f9c3bbb8-94d7-4053-a9f5-d9a6e3c88c51.png)

I commented those lines and replaced with a new version of the computations without the EnergyCarrierSplit. 
Results seem correct, but it should be checked if computations work as intended.
![image](https://user-images.githubusercontent.com/98351491/218452781-6efe6350-b3f1-4f7b-aa97-20abc349cc4a.png)

Same for nrb, but I have not fixed it yet.

**Comment by stefanpauliuk** [comment]
It definitely needs to look like in the Figure below, which it did before in RECC v2.4. I will double-check the entire energy calculation for historic and future age-cohorts.

**Comment by stefanpauliuk** [comment]
Fixed during latest RECC model update for res. and non-res buldings.
