### ISSUE TITLE
Cement/concrete are not recycled

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#44]
Cement and concrete never get recycled, in any scenario.
Current parameter 4_PY_EoL_RecoveryRate (V2.4) modules the rate of waste recovery from EoL products by multiplication with F_8_9 (the input of waste management industries). Some products actually have some concrete content recycled as  "construction waste, concrete, bricks, tiles, ceramics", but F_8_9 always have 0 flows for concrete, because concrete is split between cement and aggregates in the code. Since cement and aggregates are not waste of any product in 4_PY_EoL_RecoveryRate_2.4, they are also not recycled.

Even if the flows above were consistent, all the waste has to be remelted in process 12 before being available as secondary material, and there is no reference in 4_PY_MaterialProductionRemelting_V2.3 to any mineral. Despite the #"emelting" name might imply that only metals could become available as secondary material, you can find also wood and plastics as remelted products. I wonder if the parameter is used as Reclycing, and not Remelting.

Currently, only way to give second life to minerals is to activate the Re-Use ME strategy, but there is no baseline recycling.

**Comment by stefanpauliuk** [comment]
Hi @CarrerF , we do have a small potential for the re-use of concrete, typically done by reusing concrete slabs.
Concrete reycling can be done, but only aggregates can be recoverd, and they need new cement as binder.
The current state of the knowledge is that recovering aggregates from concrete is a resource savings strategy, as it can reduce the amoung of sand and gravel needed, but not an emissoins reductoin strategy, see here: https://doi.org/10.1016/j.resconrec.2021.105767 
Currently, it is implicitly assumed that all recovered crushed concrete either stays on the side as filling or goes into infrastructure construction. So more of an open system. As we move towards also including infrastructure in RECC v2.6, we will have to rethink this issue and add a scenario for recovering aggregates and send them to different end-use sectors.
