### ISSUE TITLE
3_EI_Products_UsePhase_resbuildings.xlsx file with a #REF problem

### ISSUE THREAD

**Issue by leandrocfg** [IndEcol/RECC-ODYM#45]
Hi, 

I've got some errors while running the code. The following error was given:
"ValueError: could not convert string to float: '#REF!'".

It happened while reading the 3_EI_Products_UsePhase_resbuildings.xlsx file downloaded from the v2.4 database in Zenodo.
Opening the file, cells BM698 to BQ698 have a reference error (#REF).

The second is in line 345, it returned the following error:
"ValueError: 'production of cast Al, efficient' is not in list".
Checking the RECC_Classification_Master_v2.0, also obtained from the RECC v2.4 repository in Zenodo, I have noticed that there is no "production of cast Al, efficient" item in Material_Production_i2 spreadsheet, as there is no "production of wrought Al, efficient".

Regards,

**Comment by stefanpauliuk** [comment]
Hi @leandrocfg , yes, this file has some bugs insinde indeed, please check whether this fixed version works for you:
https://www.dropbox.com/s/zyy6wwfve14687f/3_EI_Products_UsePhase_resbuildings_V1.3.xlsx?dl=0 
Best regards,
Stefan

**Comment by stefanpauliuk** [comment]
Regarding the 'production of cast Al, efficient': This is part of the current RECC version v2.5.
For recreating the RECC v2.4, you need to set the git repo to the commit that is given in the paper:

The model code is available on GitHub via https://github.com/YaleCIE/RECC-ODYM (commit f2f59c4) and https://github.com/IndEcol/ODYM (commit 3f65f98).

Note that this may require a legacy version of xlrd.

**Comment by leandrocfg** [comment]
Hi, @stefanpauliuk,

Thank you for your answer. I also found the same error for others parameters, like the production of different steels using H2 and used construction wood. 
What I could understand is that version 2.5 will need a new Classification_Master table version and that the parameters database will need further data, e.g., in 4_EI_ProcessEnergyIntensity, only steel/iron processes EI are available, no data for AL or cement is available. What I couldn't understand is if their are already available or are still under construction

Best regards,
Leandro

**Comment by stefanpauliuk** [comment]
Fixed during major update on how me model material production and energy supply.
