### ISSUE TITLE
Move to IndEcol or Freiburg (not urgent)

### ISSUE THREAD

**Issue by konstantinstadler** [IndEcol/RECC-ODYM#47]
Just to start the discussion here, perhaps we later also have to involve Edgar.
But is there a reasons to still have it on YaleCIE? Could we move that to IndEcol to highlight cross-institute efforts or to an open freiburg repo?

**Comment by stefanpauliuk** [comment]
Hi @konstantinstadler I am all for moving it to https://github.com/IndEcol

**Comment by konstantinstadler** [comment]
Should we just do, or first discuss with Edgar?
________________________________

**Comment by Hertwich** [comment]
Feel free to move it. I have no objections.

**Comment by konstantinstadler** [comment]
Oh, Edgar is on GitHub too - good to know🤓

**Comment by nheeren** [comment]
Hey there. Stefan and I discussed the same thing a few weeks ago. This repo is about the UNEP report, i.e. one particular application of ODYM. And that was started at Yale. Also there are probably a few links out there that refer to this repo here. I don't mind moving, but there should be a referrer to the new location then.

**Comment by konstantinstadler** [comment]
If you transfer with the Github transfer functionality, this is automatically taken care of (as long as yale does not start another project with the same name/url). E.g. I moved pymrio some month ago to IndEcol - www.github.com/konstantinstadler/pymrio still automaatically refers to it

________________________________

**Comment by nheeren** [comment]
Done then :)

**Comment by konstantinstadler** [comment]
Welcome at indecol
