### ISSUE TITLE
Additions to 4_PE_ProcessExtensions_Industry

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#59]
The LCA report I use to compile 4_PE_ProcessExtensions_Industry did not include values for biomass-based electricity, and the dataset is currently missing them.

As I now see that the dataset has been extended with other midpoints, same sources/assumptions for RMI and primary energy for biomass electricity could be replicated also for other impacts.

**Comment by stefanpauliuk** [comment]
Good point @CarrerF !
I added a rought estimate of the GHG and water use for biomass-based electricity, see
4_PE_ProcessExtensions_Industry_V1.2.
