### ISSUE TITLE
Missing new materials in the classification  

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#69]
@stefanpauliuk I am not sure if the classification master on Dropbox is the one you used for producing the latest set of results, but we noted that there is a mismatch for some new materials.

**Glass** and **Insulation** are listed in Material_Production_i2, but not in Engineering_Materials_m2.
We have already collected data in 4_PE_ProcessExtensions_Materials and in 4_EI_ProcessEnergyIntensity, and linked materials to processes in 4_SHA_MaterialsTechnologyShare, so they would be ready to be used.

On the contrary, **Bricks** are listed in Engineering_Materials_m2, but not in Material_Production_i2, so they are in the stock but do not have any production impact. Data in 4_PE_ProcessExtensions_Materials, 4_EI_ProcessEnergyIntensity and 4_SHA_MaterialsTechnologyShare are also missing.

New non-residential archetypes have non-zero brick intensity, so their contribution is missing.

Also, if I remember correctly, residential archetypes (and maybe non-res too) had some glass and insulation, which were aggregated to Other materials. There is room for refinement here, assigning them in BuildME to their corresponding material class.

**Comment by stefanpauliuk** [comment]
Hi @CarrerF Indeed, these materials haven't been considered so far.

I propose to add the following (see curent Master Classification file):

add to Engineering_Materials_m2:
glass
insulation material

add to Material_Production_i2:
production of bricks from clay

So these can now be selected in the config file and existing data can be used!
Different type of insulation material (fibre-based, plastic-based, rock wool) can be implemented via their different impacts (MF, GHG, energy consumption in production).

still to be done: 
+ Add energy requirements and footprints of bricks --> I propose that I do this over the weekend!

+ Check the "Other materials" group of the building archetypes. Here, I have an email from Niko that sais that it can be done in principle, and that Kamila knows how to operate the code. 
The material aggregation settings are listed here:
[https://github.com/nheeren/BuildME/blob/0e218b5a66d721da1e1e6b3b2d35d67e1fb15c5f/BuildME/settings.py#L553](https://github.com/nheeren/BuildME/blob/0e218b5a66d721da1e1e6b3b2d35d67e1fb15c5f/BuildME/settings.py#L553) 
Glass and insulation are crucial for the buildings energy balance and should be included I think. I'll forward you the email (in German though), and I propose that you take a closer look at it if you wantto focus on these materials!

**Comment by stefanpauliuk** [comment]
Brick production energy use and material footprint is now included in
\Dropbox\RECC_v2_5_v2_6\data\CURRENT_V2_5\
4_EI_ProcessEnergyIntensity_V3.2
4_PE_ProcessExtensions_Materials_V1.2
See also the updated master classification as described above:
RECC_Classifications_Master_V2.0

**Comment by CarrerF** [comment]
Thanks Stefan!
@LolaRousseau might be useful for you as well

**Comment by LolaRousseau** [comment]
Great, thanks @stefanpauliuk and @CarrerF! I plan to include the materials in the version of ODYM-RECC that I have, very nice to have the updated files to look at :)
