### ISSUE TITLE
3_SHA_CementContentReduction multiplier might need revision

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#73]
Currently, the ULD ME strategy scales all the cement in the archetypes:

`if ScriptConfig['Include_REStrategy_UsingLessMaterialByDesign'] == 'True':`
`Par_RECC_MC_Nr[115::,**Cement_loc**,:,:,mS,:] = Par_RECC_MC_Nr[115::,Cement_loc,:,:,mS,:] * 
(1 - RECC_System.ParameterDict['3_SHA_CementContentReduction'].Values[Cement_loc] * 
np.einsum('oc,gt->cgot',RECC_System.ParameterDict['3_SHA_RECC_REStrategyScaleUp'].Values[mR,:,:,mS],np.ones((Ng,Nt)))).copy() `

This was okay for old archetypes because all the cement was coming from concrete.
However, new archetypes have positive cement content, which should not be scaled down because cement reduction already applies at the archetype level.

The amount of cement reduction should be scaled by 3_MC_CementContentConcrete, because by definition 3_SHA_CementContentreduction is the "Share of cement **in concrete** that can be reduced or replaced by other materials", and not the total cement of a product.

**Comment by stefanpauliuk** [comment]
Hi @CarrerF, this is not a bug but a feature!

There are two strategies under ULD: 

- Less concrete per m², through better design of buildings, leads to less cement and aggregates via the use of lighweight archetypes when ULD is True.
- Less cement per ton of concrete (simulates less clinker per ton of cement), modelled separately and on top of the concrete reduction when ULD is True.

**Comment by stefanpauliuk** [comment]
Exactly, there is this extra cement demand for cement in mortar, plaster, or screed. Also here, a reduction of the clinker content is plausible so it's fully OK in my view to apply the cement content reduction to these cement flows as well.
